var a = false
try {
	throw new Exception()
}
catch(e : Exception) {
	a = true
}
assert(a)